spring.application.name=todolist

spring.datasource.url=jdbc:h2:file:./data/TodoListDB

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=andy
spring.datasource.password=1234

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true

# none: no crea, modifica ni valida el esquema - producción cuando usas Flyway o Liquibase
# validate: verifica que el esquema coincida con las entidades sin modificarlo - producción
# update: actualiza el esquema conservando los datos existentes - desarrollo
# create: elimina y vuelve a crear el esquema al iniciar - pruebas o proyectos temporales
# create-drop: crea el esquema al iniciar y lo elimina al cerrar - pruebas de integración

spring.jpa.hibernate.ddl-auto=update

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console